### PR TITLE
Adds a new configuration for CRC16 IBM-3740

### PR DESCRIPTION
**Pull request by rickie95**
Hi guys, I had to create a new configuration for this esoteric flavour, if you find it useful feel free to merge this request.

Values are taken from [the crc catalogue linked in README](https://reveng.sourceforge.io/crc-catalogue/all.htm) and seem to be ok with other implementations.

```
width=16 poly=0x1021 init=0xffff refin=false refout=false xorout=0x0000 check=0x29b1 residue=0x0000
```

Let me know if you need a test case or anything else.

Great work btw!

### CODE REVIEW

**Comment by Nicoretti** [comment]
Hi @rickie95,

Thank you for your contribution :+1: ! I noticed that the default tests for the configuration is missing. Could you please add it, using the example provided in our existing tests? You can find a relevant example [here](https://github.com/Nicoretti/crc/blob/35178a559da0385b310a292a16771f0741532b21/test/unit/test_crc.py#L239). This addition would be greatly appreciated.

Additionally, it would be helpful if you could update the change-log by adding an entry for the newly added configuration in `docs/docs/changelog/unreleased.md`.

If you're unable to make these changes, I will take care of them and merge the updates.

Best,
Nico

**Comment by Nicoretti** [comment]
@rickie95 removing the `@enum.unique` decorator should allow to have multiple names for the same configuration settings.

**Comment by rickie95** [comment]
Hi Nico, thanks for your suggestions, I opened the PR without checking for test, my bad!

I added a relevant test and seems to pass on my Python version (3.11). As you can see from the commits the ValueError in the CRC16 enum was due to a duplicated configuration, still my mistake.

I'm looking forward to your feedback!

**Comment by Nicoretti** [comment]
@rickie95, one last thing I almost forgot: please feel free to add yourself to the contributors list in `docs/docs/contributors.md`.

**Review by Nicoretti — APPROVED** [review]

**Pull request merged**
